# Generated by Django 2.2.5 on 2019-09-04 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Имя', max_length=50)),
                ('surname', models.CharField(help_text='Фамилия', max_length=50)),
                ('patronymic', models.CharField(blank=True, help_text='Отчество', max_length=50, null=True)),
                ('nickname', models.CharField(help_text='Никнейм', max_length=50)),
            ],
            options={
                'ordering': ['name', 'surname', 'patronymic'],
            },
        ),
        migrations.CreateModel(
            name='CrosswordBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название кроссворда', max_length=50)),
                ('comment', models.TextField(help_text='Комментарий')),
                ('file', models.FileField(upload_to='')),
                ('date', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(help_text='Автор', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Django_Site.Author')),
            ],
            options={
                'ordering': ['name', '-date'],
            },
        ),
    ]
