# Generated by Django 2.2.5 on 2019-09-05 16:18

import Django_Site.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Django_Site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crosswordbase',
            name='file',
            field=models.FileField(upload_to=Django_Site.models.directory_path),
        ),
    ]
